version: '3.8'

services:
  backend:
    build: .
    container_name: express-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # важно: не затирай node_modules хостовой системой
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=testdb
    command: npm run dev

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
